name: opypackage standard
on:
  push:
    branches:
      - develop

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: pip build and publish
        uses: openergy/ogithub-actions/actions/opypackage-pip-build-and-publish-v1@develop
        with:
          admin-github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          pypi-openergy-password: ${{ secrets.PYPI_OPENERGY_PASSWORD }}
