name: opypackage standard
on:
  push:
    branches:
      - develop

jobs:
  openergy:
    uses: openergy/github-actions-workflows/.github/workflows/opypackage-standard-v02.yml@master
    with:
      publish-to-pypi: true

    secrets:
      AZURE_CONDA_CHANNEL_KEY: ${{ secrets.AZURE_CONDA_CHANNEL_KEY }}
      CONDA_CHANNEL_SYSADMIN_URL: ${{ secrets.CONDA_CHANNEL_SYSADMIN_URL }}
      ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
      PYPI_OPENERGY_PASSWORD: ${{ secrets.PYPI_OPENERGY_PASSWORD }}
